### ISSUE TITLE
0.0.54 regression in select

### ISSUE THREAD

**Issue by justinbowes** [microsoft/guidance#102]
**The bug**
Notebook `guaranteeing_valid_syntax.ipynb` works with Vicuna in 0.0.53 and not in 0.0.54.

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```python
tokenizer = transformers.LlamaTokenizer.from_pretrained(vicuna_model)
model = transformers.LlamaForCausalLM.from_pretrained(vicuna_model, load_in_8bit=True, device_map='auto')
guidance.llm = guidance.llms.transformers.Vicuna(model=model, tokenizer=tokenizer, device_map='auto')

# we can pre-define valid option sets
valid_weapons = ["sword", "axe", "mace", "spear", "bow", "crossbow"]

# define the prompt
program = guidance("""The following is a character profile for an RPG game in JSON format.
```json
{
    "description": "{{description}}",
    "name": "{{gen 'name'}}",
    "age": {{gen 'age' pattern='[0-9]+' stop=','}},
    "armor": "{{#select 'armor'}}leather{{or}}chainmail{{or}}plate{{/select}}",
    "weapon": "{{select 'weapon' options=valid_weapons}}",
    "class": "{{gen 'class'}}",
    "mantra": "{{gen 'mantra'}}",
    "strength": {{gen 'strength' pattern='[0-9]+' stop=','}},
    "items": [{{#geneach 'items' num_iterations=3}}
        "{{gen 'this'}}",{{/geneach}}
    ]
}```""")

# execute the prompt
out = program(description="A quick and nimble fighter", valid_weapons=valid_weapons)
```

# result in 0.0.53:
The following is a character profile for an RPG game in JSON format.
```json
{
    "description": "A quick and nimble fighter",
    "name": "Raphael",
    "age": 25,
    "armor": "leather",
    "weapon": "spear",
    "class": "fighter",
    "mantra": "Strike fast, strike hard.",
    "strength": 16,
    "items": [
        "health potion",
        "magic potion",
        "gold",
    ]
}
```

# result in 0.0.54:
The following is a character profile for an RPG game in JSON format.
```json
{
    "description": "A quick and nimble fighter",
    "name": "
Traceback (most recent call last):
  File "/srv/lab/guidance/_program_executor.py", line 94, in run
    await self.visit(self.parse_tree)
  File "/srv/lab/guidance/_program_executor.py", line 429, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/srv/lab/guidance/_program_executor.py", line 429, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/srv/lab/guidance/_program_executor.py", line 396, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "/srv/lab/guidance/library/_select.py", line 139, in select
    option_logprobs = await recursive_select([])
  File "/srv/lab/guidance/library/_select.py", line 115, in recursive_select
    assert len(ids) == 1
```

# Modifying the assertion in 0.0.54 for more information:
```
L115: assert len(ids) == 1, f'{k}: {ids} < {logprobs_result}'

AssertionError: le: [] / {'token_healing_prefix': '', 'top_logprobs': [{'le': tensor(-0.6333, dtype=torch.float16), 'chain': tensor(-0.8833, dtype=torch.float16), 'plate': tensor(-2.8828, dtype=torch.float16)}]}
```

**System info (please complete the following information):**
 - OS: Ubuntu 20.04, NVIDIA CUDA 11.6 container
 - Guidance Version (`guidance.__version__`): 0.0.54

**Comment by slundberg** [comment]
Thanks, that looks like a tokenization issue with sentencepeice, I'll look into it tomorrow and push a fix.

**Comment by justinbowes** [comment]
Thank you. Loving the project and appreciating the rapid turnaround!
