### ISSUE TITLE
Error running demos: use_clear_syntax.ipynb

### ISSUE THREAD

**Issue by wooparadog** [microsoft/guidance#13]
Hi,

Firstly, thanks for sharing the idea of prompt templating.

I'm playing with use_clear_syntax.ipynb in `notebooks/art_of_prompt_design/use_clear_syntax.ipynb`, 
and trying to understand how it works with openai API using the following code:

https://gist.github.com/wooparadog/5765952394c33c5c9091f2835467eeec

But I got an exception:

```
Traceback (most recent call last):
  File "/home/wooparadog/Codes/github.com/microsoft/guidance/guidance/_program_executor.py", line 94, in run
    await self.visit(self.parse_tree)
  File "/home/wooparadog/Codes/github.com/microsoft/guidance/guidance/_program_executor.py", line 434, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wooparadog/Codes/github.com/microsoft/guidance/guidance/_program_executor.py", line 434, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wooparadog/Codes/github.com/microsoft/guidance/guidance/_program_executor.py", line 394, in visit
    command_output = await command_function(*positional_args, **named_args)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wooparadog/Codes/github.com/microsoft/guidance/guidance/library/_system.py", line 13, in system
    return await role(name="system", hidden=hidden, _parser_context=_parser_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wooparadog/Codes/github.com/microsoft/guidance/guidance/library/_role.py", line 4, in role
    block_content = _parser_context['block_content']
                    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

``` 

Is there anything wrong with my test case? Thanks again

**Comment by wooparadog** [comment]
More info:

I'm using guidance==0.0.42 and running on Linux Python 3.11.3

And I also failed with the first case in README.md

**Comment by slundberg** [comment]
Thanks! A typo got into pypi version, should be fixed now.
