### ISSUE TITLE
role_simulator function raises "Exception: Error generating stop tokens for geneach loop."

### ISSUE THREAD

**Issue by Keiku** [microsoft/guidance#172]
**The bug**

`role_simulator` function raises "Exception: Error generating stop tokens for geneach loop."

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.

```python
import guidance
import re
guidance.llm = guidance.llms.OpenAI("gpt-3.5-turbo")
role_simulator = guidance('''
{{#system~}}
You are a helpful assistant
{{~/system}}

{{#user~}}
You will answer the user as {{role}} in the following conversation. At every step, I will provide you with the user input, as well as a comment reminding you of your instructions. Never talk about the fact that you are an AI, even if the user asks you. Always answer as {{role}}.
{{#if first_question}}You can also start the conversation.{{/if}}
{{~/user}}

{{~! The assistant either starts the conversation or not, depending on if this is the first or second agent }}
{{#assistant~}}
Ok, I will follow these instructions.
{{#if first_question}}Let me start the conversation now:
{{role}}: {{first_question}}{{/if}}
{{~/assistant}}

{{~! Then the conversation unrolls }}
{{~#geneach 'conversation'}}
{{#user~}}
User: {{set 'this.input' (await 'input')}}
Comment: Remember, answer as a {{role}}. Start your utterance with {{role}}:
{{~/user}}

{{#assistant~}}
{{gen 'this.response' temperature=0 max_tokens=300}}
{{~/assistant}}
{{~/geneach}}''')

republican = role_simulator(role='Republican', await_missing=True)
democrat = role_simulator(role='Democrat', await_missing=True)

first_question = '''What do you think is the best way to stop inflation?'''
republican = republican(input=first_question, first_question=None)
democrat = democrat(input=republican["conversation"][-2]["response"].strip('Republican: '), first_question=first_question)
for i in range(2):
    republican = republican(input=democrat["conversation"][-2]["response"].replace('Democrat: ', ''))
    democrat = democrat(input=republican["conversation"][-2]["response"].replace('Republican: ', ''))

print('Democrat: ' + first_question)
for x in democrat['conversation'][:-1]:
    print('Republican:', x['input'])
    print()
    print(x['response'])
```

Below is the output.

```python
system
You are a helpful assistant
user
You will answer the user as Republican in the following conversation. At every step, I will provide you with the user input, as well as a comment reminding you of your instructions. Never talk about the fact that you are an AI, even if the user asks you. Always answer as Republican.
assistant
Ok, I will follow these instructions.
user
User: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/guidance/library/_geneach.py", line 146, in geneach
    if gen_obj["choices"][0]["finish_reason"] == "stop":
  File "/usr/local/lib/python3.10/dist-packages/guidance/llms/_openai.py", line 525, in __call__
  File "/usr/local/lib/python3.10/dist-packages/guidance/llms/_openai.py", line 310, in _library_call
    if self.chat_mode:
  File "/usr/local/lib/python3.10/dist-packages/guidance/llms/_openai.py", line 24, in prompt_to_messages
    matches = re.findall(pattern, prompt, re.DOTALL)
AssertionError: When calling OpenAI chat models you must generate only directly inside the assistant role! The OpenAI API does not currently support partial assistant prompting.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 102, in run
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 437, in visit
    parts = re.split(r"\.|\[", name)
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 437, in visit
    parts = re.split(r"\.|\[", name)
  File "/usr/local/lib/python3.10/dist-packages/guidance/_program_executor.py", line 404, in visit
    self.block_content.pop()
  File "/usr/local/lib/python3.10/dist-packages/guidance/library/_geneach.py", line 148, in geneach
Exception: Error generating stop tokens for geneach loop. Perhaps you are outside of role tags (assistant/user/system)? If you don't want the loop to check for stop tokens, set stop=False or set num_iterations.

Error in program:  Error generating stop tokens for geneach loop. Perhaps you are outside of role tags (assistant/user/system)? If you don't want the loop to check for stop tokens, set stop=False or set num_iterations.
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/guidance/library/_geneach.py](https://localhost:8080/#) in geneach(list_name, stop, max_iterations, min_iterations, num_iterations, hidden, join, single_call, single_call_temperature, single_call_max_tokens, single_call_top_p, _parser_context)
    145                     raise Exception(f"Error generating stop tokens for geneach loop. Perhaps you are outside of role tags (assistant/user/system)? If you don't want the loop to check for stop tokens, set stop=False or set num_iterations.")
--> 146                 if gen_obj["choices"][0]["finish_reason"] == "stop":
    147                     break

14 frames
AssertionError: When calling OpenAI chat models you must generate only directly inside the assistant role! The OpenAI API does not currently support partial assistant prompting.

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/guidance/library/_geneach.py](https://localhost:8080/#) in geneach(list_name, stop, max_iterations, min_iterations, num_iterations, hidden, join, single_call, single_call_temperature, single_call_max_tokens, single_call_top_p, _parser_context)
    146                 if gen_obj["choices"][0]["finish_reason"] == "stop":
    147                     break
--> 148 
    149     # TODO: right now single_call is a bit hacky, we should make it more robust to rich loop item template structures
    150     else: # if single_call

Exception: Error generating stop tokens for geneach loop. Perhaps you are outside of role tags (assistant/user/system)? If you don't want the loop to check for stop tokens, set stop=False or set num_iterations.
```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.):

Colab Pro+: A100 GPU

 - Guidance Version (`guidance.__version__`):

```python
0.0.59
```

**Comment by slundberg** [comment]
Thanks! That was an error in one of the notebook examples. As the error message states, you need to set `stop=False` for the geneach command here so it loops forever, otherwise it tries to call the LLM to check if the loop should continue, which can't be done here since chatGPT does not allow calls outside of role tags.

**Comment by Keiku** [comment]
@slundberg Thanks for mentioning `stop=False`. However, even in the latest version, it is not as follows. please confirm.

[chat.ipynb](https://github.com/microsoft/guidance/tree/main/notebooks/chat.ipynb)
```python
republican = role_simulator(role='Republican', await_missing=True)
democrat = role_simulator(role='Democrat', await_missing=True)
```
