### ISSUE TITLE
ImportError: cannot import name '_tiktoken' from partially initialized module 'tiktoken'

### ISSUE THREAD

**Issue by talglobus** [microsoft/guidance#331]
**The bug**
It seems there's some circular import problem with tiktoken. Running just the code below, with no additional imports, I'm getting the error below.

**To Reproduce**

```python
import guidance
gpt4 = guidance.llms.OpenAI("gpt-4")

---------------------------------------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/me/superscan/env/lib/python3.11/site-packages/guidance/llms/_openai.py", line 177, in __init__
    import tiktoken
  File "/Users/me/superscan/env/lib/python3.11/site-packages/tiktoken/__init__.py", line 1, in <module>
    from .core import Encoding as Encoding
  File "/Users/me/superscan/env/lib/python3.11/site-packages/tiktoken/core.py", line 9, in <module>
    from tiktoken import _tiktoken
ImportError: cannot import name '_tiktoken' from partially initialized module 'tiktoken' (most likely due to a circular import) (/Users/me/superscan/env/lib/python3.11/site-packages/tiktoken/__init__.py)
```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Mac OS 13.3.1
 - Guidance Version (`guidance.__version__`): 0.0.64

**Comment by talglobus** [comment]
Resolved by switching from vanilla Pip to Poetry, likely a dependency conflict
