### ISSUE TITLE
"Unrecognized request argument supplied: logprobs" Error with Azure OpenAI Service

### ISSUE THREAD

**Issue by wwwcojp** [microsoft/guidance#89]
**The bug**
I ran [tutorial.ipynb](https://github.com/microsoft/guidance/blob/main/notebooks/tutorial.ipynb) using Azure OpenAI Service and got the following error in the Chat section.

**error messages**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/guidance/_program_executor.py", line 94, in run
    await self.visit(self.parse_tree)
  File "/usr/local/lib/python3.9/site-packages/guidance/_program_executor.py", line 428, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.9/site-packages/guidance/_program_executor.py", line 428, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.9/site-packages/guidance/_program_executor.py", line 395, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "/usr/local/lib/python3.9/site-packages/guidance/library/_assistant.py", line 13, in assistant
    return await role(name="assistant", hidden=hidden, _parser_context=_parser_context)
  File "/usr/local/lib/python3.9/site-packages/guidance/library/_role.py", line 14, in role
    out = await parser.visit(
  File "/usr/local/lib/python3.9/site-packages/guidance/_program_executor.py", line 428, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.9/site-packages/guidance/_program_executor.py", line 428, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.9/site-packages/guidance/_program_executor.py", line 218, in visit
    visited_children = [await self.visit(child, next_node, next_next_node, prev_node, node, parent_node) for child in node.children]
  File "/usr/local/lib/python3.9/site-packages/guidance/_program_executor.py", line 218, in <listcomp>
    visited_children = [await self.visit(child, next_node, next_next_node, prev_node, node, parent_node) for child in node.children]
  File "/usr/local/lib/python3.9/site-packages/guidance/_program_executor.py", line 428, in visit
    visited_children.append(await self.visit(child, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/usr/local/lib/python3.9/site-packages/guidance/_program_executor.py", line 292, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "/usr/local/lib/python3.9/site-packages/guidance/library/_gen.py", line 132, in gen
    gen_obj = await parser.llm_session(
  File "/usr/local/lib/python3.9/site-packages/guidance/llms/_openai.py", line 466, in __call__
    out = self.llm.caller(**call_args)
  File "/usr/local/lib/python3.9/site-packages/guidance/llms/_openai.py", line 310, in _rest_call
    raise Exception("Response is not 200: " + response.text)
Exception: Response is not 200: {
  "error": {
    "message": "Unrecognized request argument supplied: logprobs",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

**To Reproduce**

```python
import guidance
guidance.llm = guidance.llms.AzureOpenAI("gpt-3.5-turbo",
                endpoint="https://<endpoint url>",
                client_id="<client id(application id)>", 
                authority="https://login.microsoftonline.com/<Azure AD tenant id>",
                scopes=["https://cognitiveservices.azure.com/.default"],
                caching=False)

program = guidance('''
{{#system~}}
You are a helpful assistant.
{{~/system}}

{{#user~}}
{{conversation_question}}
{{~/user}}

{{! this is a comment. note that we don't have to use a stop="stop_string" for the gen command below because Guidance infers the stop string from the role tag }}
{{#assistant~}}
{{gen 'response'}}
{{~/assistant}}''')

executed_program = program(conversation_question='What is the meaning of life?')
```

**Possible Solution**
ChatCompletion API does not accept logprobs argument.
If the endpoint argument is not specified, _library_call is called and the logprobs argument is deleted.
https://github.com/microsoft/guidance/blob/637a9d3d8f9fb79a24a18b77f4c4d9fc8d12b630/guidance/llms/_openai.py#L265-L269
If the endpoint argument is specified, _rest_call is called and the logprobs argument is not deleted.
https://github.com/microsoft/guidance/blob/637a9d3d8f9fb79a24a18b77f4c4d9fc8d12b630/guidance/llms/_openai.py#L301-L305
Therefore, it would be sufficient to delete the logprobs argument even for _rest_call.

**System info (please complete the following information):**
 - OS (Debian 10):
 - Guidance Version (0.0.53):

**Comment by slundberg** [comment]
Thanks! If you want to push a PR for that fix go for it. Otherwise I can do that as well.

**Comment by wwwcojp** [comment]
Would you mind fixing it, please?
